name: develop-deploy
on: 
  push:
    branches:
      - 'develop'
jobs:
  changed_dir:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.changes.outputs.dir}}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed directory
        id: changes
        run: |
          echo "::set-output name=dir::$(git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq)"
  lint:
    runs-on: ubuntu-latest
    needs: changed_dir
    # only run there are changed files
    if: ${{needs.changed_dir.outputs.dir}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changed_dir.outputs.dir}}