
name: feature-pylint
on: 
  push:
    branches:
      - 'feature-*'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.changes.outputs.dir}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pylint-score
        id: pylint
        run: |
          if [[ ${GITHUB_REF##*/} == *feature* ]]; then
            echo "Running on ${GITHUB_REF##*/}"
            /home/runner/work/lamdba-ci-cd-demo/lamdba-ci-cd-demo/ci-scripts/py-lint.sh "${GITHUB_SHA}"
          fi
      - name: terraform-validation 
        id: validate-tf-code
        run: |
          if [[ ${GITHUB_REF##*/} == *feature* ]]; then
            echo "Running on ${GITHUB_REF##*/}"
            /home/runner/work/lamdba-ci-cd-demo/lamdba-ci-cd-demo/ci-scripts/tf-validate.sh "${GITHUB_SHA}"
          fi