
name: feature-pylint
on: 
  push:
    branches:
      - 'feature-*'
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.changes.outputs.dir}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: pylint-score
        id: pylint
        run: |
          if [[ ${GITHUB_REF##*/} == *feature/* ]]; then
            echo "Running on ${GITHUB_REF##*/}"
            pwd && ls -lthr
          fi