
name: ci-dags
on: 
  push:
   
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.changes.outputs.dir}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get changed directory
        id: changes
        run: |
          echo "::set-output name=dir::$(git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq)
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{ needs.job1.outputs.dir}}